Repository letsgetit-hanwha-be15/be15-2nd-letsgetit-newbit, pull requests merged in 2025-04, with the labels that each got.

#48 initial commit
  .gitattributes
  .gitignore
  .gradle/8.13/checksums/checksums.lock
  .gradle/8.13/executionHistory/executionHistory.lock
  .gradle/8.13/fileChanges/last-build.bin
  .gradle/8.13/fileHashes/fileHashes.bin
  .gradle/8.13/fileHashes/fileHashes.lock
  .gradle/8.13/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/newbit/NewbitApplication.java
  src/main/java/com/newbit/common/config/JpaConfig.java
  src/main/java/com/newbit/common/config/ModelMapperConfig.java
  src/main/java/com/newbit/common/dto/ApiResponse.java
  src/main/java/com/newbit/common/dto/Pagination.java
  src/main/java/com/newbit/common/exception/BusinessException.java
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/common/exception/GlobalExceptionHandler.java
  src/main/java/com/newbit/common/service/FileStorageService.java
  src/test/java/com/newbit/newbit/NewbitApplicationTests.java
Labels: feat

#140 Nbt 78 be 멘토 칼럼 등록 요청 기능 구현
  build.gradle
  src/main/java/com/newbit/column/controller/ColumnRequestController.java
  src/main/java/com/newbit/column/dto/request/CreateColumnRequestDto.java
  src/main/java/com/newbit/column/dto/response/CreateColumnResponseDto.java
  src/main/java/com/newbit/column/entity/Column.java
  src/main/java/com/newbit/column/entity/ColumnRequest.java
  src/main/java/com/newbit/column/enums/RequestType.java
  src/main/java/com/newbit/column/mapper/ColumnMapper.java
  src/main/java/com/newbit/column/repository/ColumnRepository.java
  src/main/java/com/newbit/column/repository/ColumnRequestRepository.java
  src/main/java/com/newbit/column/service/ColumnRequestService.java
  src/test/java/com/newbit/column/controller/ColumnRequestControllerTest.java
Labels: feat

#141 Nbt 79 be 멘토 칼럼 수정 요청 기능 구현
  src/main/java/com/newbit/column/controller/ColumnRequestController.java
  src/main/java/com/newbit/column/dto/request/UpdateColumnRequestDto.java
  src/main/java/com/newbit/column/dto/response/UpdateColumnResponseDto.java
  src/main/java/com/newbit/column/service/ColumnRequestService.java
  src/test/java/com/newbit/column/controller/ColumnRequestControllerTest.java
Labels: feat

#149 Nbt 92 be 게시글 수정 기능 구현
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/dto/PostDto.java
  src/main/java/com/newbit/post/entity/Post.java
  src/main/java/com/newbit/post/repository/PostRepository.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#162 Nbt 65 be 회원 가입 기능 구현
  build.gradle
  src/main/java/com/newbit/common/config/SecurityConfig.java
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/user/controller/UserController.java
  src/main/java/com/newbit/user/dto/request/UserRequestDTO.java
  src/main/java/com/newbit/user/entity/Authority.java
  src/main/java/com/newbit/user/entity/User.java
  src/main/java/com/newbit/user/repository/UserRepository.java
  src/main/java/com/newbit/user/service/UserService.java
  src/test/java/com/newbit/user/service/UserServiceTest.java
Labels: feat

#172 Nbt 116 be 회원 아이디 찾기 기능 구현
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/user/controller/UserController.java
  src/main/java/com/newbit/user/dto/request/FindIdDTO.java
  src/main/java/com/newbit/user/dto/response/UserIdDTO.java
  src/main/java/com/newbit/user/repository/UserRepository.java
  src/main/java/com/newbit/user/service/UserService.java
  src/test/java/com/newbit/user/service/FindEmailByNameAndPhoneTest.java
Labels: feat

#184 feat: NBT-93 게시글 삭제 기능 구현
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/dto/request/PostUpdateRequest.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#185 Nbt 86 be 공개된 칼럼 상세 조회 기능 구현
  src/main/java/com/newbit/column/controller/ColumnController.java
  src/main/java/com/newbit/column/domain/Column.java
  src/main/java/com/newbit/column/dto/response/GetColumnDetailResponseDto.java
  src/main/java/com/newbit/column/dto/response/UpdateColumnResponseDto.java
  src/main/java/com/newbit/column/service/ColumnService.java
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/purchase/query/service/ColumnPurchaseHistoryQueryService.java
  src/test/java/com/newbit/column/service/ColumnServiceTest.java
Labels: feat

#186 Nbt 118 be 회원 비밀번호 찾기 기능 구현
  build.gradle
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/user/controller/UserController.java
  src/main/java/com/newbit/user/dto/request/FindPasswordDTO.java
  src/main/java/com/newbit/user/entity/User.java
  src/main/java/com/newbit/user/repository/UserRepository.java
  src/main/java/com/newbit/user/service/UserService.java
  src/main/java/com/newbit/user/support/MailServiceSupport.java
  src/test/java/com/newbit/user/service/FindEmailByNameAndPhoneTest.java
  src/test/java/com/newbit/user/service/FindpasswordByEmailTest.java
Labels: feat

#187 feat: NBT-98 게시글 검색 기능 구현
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/repository/PostRepository.java
  src/main/java/com/newbit/post/service/PostService.java
Labels: feat

#189 feat: NBT-103 댓글 등록 기능 구현
  src/main/java/com/newbit/post/controller/CommentController.java
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/dto/request/CommentCreateRequest.java
  src/main/java/com/newbit/post/dto/response/CommentResponse.java
  src/main/java/com/newbit/post/entity/Comment.java
  src/main/java/com/newbit/post/repository/CommentRepository.java
  src/main/java/com/newbit/post/service/CommentService.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/CommentServiceTest.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#190 Nbt 114 be 로그인 기능 구현
  src/main/java/com/newbit/auth/controller/AuthController.java
  src/main/java/com/newbit/auth/dto/request/LoginRequestDTO.java
  src/main/java/com/newbit/auth/dto/request/RefreshTokenRequestDTO.java
  src/main/java/com/newbit/auth/dto/response/TokenResponseDTO.java
  src/main/java/com/newbit/auth/entity/RefreshToken.java
  src/main/java/com/newbit/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/newbit/auth/jwt/JwtTokenProvider.java
  src/main/java/com/newbit/auth/jwt/RestAccessDeniedHandler.java
  src/main/java/com/newbit/auth/jwt/RestAuthenticationEntryPoint.java
  src/main/java/com/newbit/auth/model/CustomUser.java
  src/main/java/com/newbit/auth/repository/RefreshTokenRepository.java
  src/main/java/com/newbit/auth/service/AuthService.java
  src/main/java/com/newbit/auth/service/CustomUserDetailsService.java
  src/main/java/com/newbit/auth/utils/HMACKeyGenerator.java
  src/main/java/com/newbit/common/config/SecurityConfig.java
  src/main/java/com/newbit/user/entity/User.java
  src/test/java/com/newbit/auth/service/AuthServiceTest.java
  src/test/java/com/newbit/auth/service/CustomUserDetailsServiceTest.java
Labels: feat

#191 Nbt 99 be 게시글 목록 조회 기능 구현
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/dto/response/PostListResponse.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#192 Nbt 102 be 댓글 조회 기능 구현
  src/main/java/com/newbit/post/controller/CommentController.java
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/repository/CommentRepository.java
  src/main/java/com/newbit/post/service/CommentService.java
  src/test/java/com/newbit/post/service/CommentServiceTest.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#193 fix: postservice-error 수정
  src/main/java/com/newbit/post/service/PostService.java
Labels: feat

#194 fix: postservicetest-error 수정
  src/main/java/com/newbit/post/controller/CommentController.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: bug

#196 Nbt 104 be 댓글 삭제 기능 구현
  src/main/java/com/newbit/post/controller/CommentController.java
  src/main/java/com/newbit/post/service/CommentService.java
  src/test/java/com/newbit/post/service/CommentServiceTest.java
Labels: feat

#198 feat: NBT-71 멘토 권한 구매 기능 구현
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/purchase/command/application/controller/PurchaseCommandController.java
  src/main/java/com/newbit/purchase/command/application/dto/MentorAuthorityPurchaseRequest.java
  src/main/java/com/newbit/purchase/command/application/service/PurchaseCommandService.java
  src/main/java/com/newbit/purchase/command/domain/aggregate/DiamondHistory.java
  src/main/java/com/newbit/purchase/command/domain/aggregate/PointHistory.java
  src/main/java/com/newbit/purchase/command/domain/aggregate/PurchaseAssetType.java
  src/main/java/com/newbit/purchase/command/domain/repository/PointHistoryRepository.java
  src/main/java/com/newbit/purchase/command/infrastructure/JpaPointHistoryRepository.java
  src/main/java/com/newbit/user/dto/response/UserDTO.java
  src/main/java/com/newbit/user/entity/Mentor.java
  src/main/java/com/newbit/user/entity/User.java
  src/main/java/com/newbit/user/service/MentorService.java
  src/main/java/com/newbit/user/service/UserService.java
  src/test/java/com/newbit/purchase/command/application/service/PurchaseCommandServiceTest.java
Labels: feat

#199 Nbt 115 be 로그아웃 기능 구현
  src/main/java/com/newbit/auth/controller/AuthController.java
  src/main/java/com/newbit/auth/service/AuthService.java
  src/test/java/com/newbit/auth/service/AuthLogOutServiceTest.java
Labels: feat

#205 feat: NBT-101 be 게시글 상세 조회 기능 구현
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/dto/response/PostDetailResponse.java
  src/main/java/com/newbit/post/entity/Post.java
  src/main/java/com/newbit/post/entity/PostCategory.java
  src/main/java/com/newbit/post/repository/PostRepository.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#203 Nbt 156 공개 칼럼 리스트 조회 기능 구현
  src/main/java/com/newbit/column/controller/ColumnController.java
  src/main/java/com/newbit/column/domain/Column.java
  src/main/java/com/newbit/column/dto/response/GetColumnDetailResponseDto.java
  src/main/java/com/newbit/column/dto/response/GetColumnListResponseDto.java
  src/main/java/com/newbit/column/mapper/ColumnMapper.java
  src/main/java/com/newbit/column/repository/ColumnRepository.java
  src/main/java/com/newbit/column/service/ColumnRequestService.java
  src/main/java/com/newbit/column/service/ColumnService.java
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/test/java/com/newbit/column/service/ColumnServiceTest.java
Labels: feat

#230 fix : Nbt 78 be 멘토 칼럼 등록 요청 기능 구현
  src/main/java/com/newbit/column/service/ColumnRequestService.java
  src/main/java/com/newbit/user/service/MentorService.java
  src/test/java/com/newbit/column/service/ColumnRequestServiceTest.java
  src/test/java/com/newbit/column/service/ColumnServiceTest.java
Labels: fix

#246 Nbt 119 be 회원 정보 조회 기능 구현
  src/main/java/com/newbit/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/newbit/auth/jwt/JwtTokenProvider.java
  src/main/java/com/newbit/common/config/SecurityConfig.java
  src/main/java/com/newbit/common/config/SwaggerConfig.java
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/user/controller/UserInfoController.java
  src/main/java/com/newbit/user/dto/response/UserDTO.java
  src/main/java/com/newbit/user/service/UserInfoService.java
  src/test/java/com/newbit/user/service/UserInfoServiceTest.java
Labels: feat

#235 feat: Nbt 161 be 본인 칼럼 요청 조회
  src/main/java/com/newbit/column/controller/ColumnRequestController.java
  src/main/java/com/newbit/column/dto/response/GetMyColumnRequestResponseDto.java
  src/main/java/com/newbit/column/mapper/ColumnMapper.java
  src/main/java/com/newbit/column/repository/ColumnRequestRepository.java
  src/main/java/com/newbit/column/service/ColumnRequestService.java
  src/main/java/com/newbit/user/repository/MentorRepository.java
  src/main/java/com/newbit/user/service/MentorService.java
  src/main/java/com/newbit/user/service/UserService.java
  src/test/java/com/newbit/column/service/ColumnRequestServiceTest.java
  src/test/java/com/newbit/column/service/ColumnServiceTest.java
Labels: feat

#215 feat: NBT-94 be 본인이 작성한 게시글 조회 기능 구현
  src/main/java/com/newbit/common/config/SwaggerConfig.java
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/repository/PostRepository.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#249 fix: SwaggerConfig class 리팩토링
  src/main/java/com/newbit/common/config/SwaggerConfig.java
Labels: bug

#242 Nbt 106 be 공지사항 등록 기능 구현
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/repository/PostRepository.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceNoticeTest.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#243 Nbt 107 be 공지사항 수정 기능 구현
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceNoticeTest.java
Labels: feat

#251 Nbt 120 be 회원 정보 수정 기능 구현
  build.gradle
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/user/controller/UserInfoController.java
  src/main/java/com/newbit/user/dto/request/UserInfoUpdateRequestDTO.java
  src/main/java/com/newbit/user/entity/User.java
  src/main/java/com/newbit/user/repository/UserRepository.java
  src/main/java/com/newbit/user/service/UserInfoService.java
  src/test/java/com/newbit/user/service/UserUpdateMyInfoTest.java
Labels: feat

#245 Nbt 105 be 공지사항 삭제 기능 구현
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceNoticeTest.java
Labels: feat

#252 feat: NBT-179 로그인, 댓글 작성, 게시글 작성시 포인트 지급 메서드 호출 추가
  src/main/java/com/newbit/auth/controller/AuthController.java
  src/main/java/com/newbit/post/service/CommentService.java
  src/main/java/com/newbit/post/service/PostService.java
  src/main/java/com/newbit/user/entity/LoginHistory.java
  src/main/java/com/newbit/user/repository/LoginHistoryRepository.java
  src/main/java/com/newbit/user/service/LoginService.java
Labels: feat

#256 Fix/로그인한 user만 게시글 등록 가능
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/CommentServiceTest.java
  src/test/java/com/newbit/post/service/PostServiceNoticeTest.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#258 Nbt 159 be 본인 칼럼 조회
  src/main/java/com/newbit/column/controller/ColumnController.java
  src/main/java/com/newbit/column/dto/response/GetMyColumnListResponseDto.java
  src/main/java/com/newbit/column/mapper/ColumnMapper.java
  src/main/java/com/newbit/column/repository/ColumnRepository.java
  src/main/java/com/newbit/column/service/ColumnRequestService.java
  src/main/java/com/newbit/column/service/ColumnService.java
  src/test/java/com/newbit/column/service/ColumnServiceTest.java
Labels: feat

#260 Nbt 181 be 회원 비밀번호 변경 기능 구현
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/user/controller/UserInfoController.java
  src/main/java/com/newbit/user/dto/request/ChangePasswordRequestDTO.java
  src/main/java/com/newbit/user/service/UserInfoService.java
  src/main/java/com/newbit/user/service/UserService.java
  src/main/java/com/newbit/user/support/PasswordValidator.java
  src/test/java/com/newbit/user/service/ChangePassswordTest.java
Labels: feat

#265 Nbt 180 be 멘토 일정 거절 기능 구현
  src/main/java/com/newbit/coffeechat/command/application/controller/CoffeechatCommandController.java
  src/main/java/com/newbit/coffeechat/command/application/dto/request/CoffeechatCreateRequest.java
  src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java
  src/main/java/com/newbit/coffeechat/command/domain/aggregate/Coffeechat.java
  src/main/resources/mappers/coffeechat/CoffeechatMapper.xml
  src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
Labels: feat

#266 Nbt 121 be 회원 탈퇴 기능 구현
  src/main/java/com/newbit/user/controller/UserInfoController.java
  src/main/java/com/newbit/user/dto/request/DeleteUserRequestDTO.java
  src/main/java/com/newbit/user/repository/UserRepository.java
  src/main/java/com/newbit/user/service/UserInfoService.java
  src/test/java/com/newbit/user/service/UnsubscribeServiceTest.java
Labels: feat

#273 Nbt 89 be 멘토의 커피챗 종료 기능 구현
  src/main/java/com/newbit/coffeechat/command/application/controller/CoffeechatCommandController.java
  src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java
  src/main/java/com/newbit/coffeechat/command/domain/aggregate/Coffeechat.java
  src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
Labels: feat

#271 fix: 게시글 수정 시 인증된 사용자만 가능하도록 기능 추가
  src/main/java/com/newbit/common/config/SwaggerConfig.java
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#274 Fix 게시글 삭제 시 인증된 사용자만 가능하도록 기능 수정
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: bug

#278 Nbt 87 be 시리즈 생성 기능 구현
  src/main/java/com/newbit/column/controller/SeriesController.java
  src/main/java/com/newbit/column/domain/Column.java
  src/main/java/com/newbit/column/domain/Series.java
  src/main/java/com/newbit/column/dto/request/CreateSeriesRequestDto.java
  src/main/java/com/newbit/column/dto/response/CreateSeriesResponseDto.java
  src/main/java/com/newbit/column/mapper/SeriesMapper.java
  src/main/java/com/newbit/column/repository/SeriesRepository.java
  src/main/java/com/newbit/column/service/SeriesService.java
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/test/java/com/newbit/column/service/SeriesServiceTest.java
Labels: feat

#280 Nbt 76 be 멘티구매확정 기능 구현
  src/main/java/com/newbit/coffeechat/command/application/controller/CoffeechatCommandController.java
  src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java
  src/main/java/com/newbit/coffeechat/command/domain/aggregate/Coffeechat.java
  src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
Labels: feat

#284 [BE] NBT-150 알림 목록 조회 기능 구현
  src/main/java/com/newbit/notification/command/application/controller/NotificationCommandController.java
  src/main/java/com/newbit/notification/command/application/dto/request/NotificationSendRequest.java
  src/main/java/com/newbit/notification/command/application/dto/response/NotificationSendResponse.java
  src/main/java/com/newbit/notification/command/application/service/NotificationCommandService.java
  src/main/java/com/newbit/notification/command/domain/repository/NotificationRepository.java
  src/main/java/com/newbit/notification/command/infrastructure/SseEmitterRepository.java
  src/main/java/com/newbit/notification/query/controller/NotificationQueryController.java
  src/main/java/com/newbit/notification/query/dto/NotificationResponse.java
  src/main/java/com/newbit/notification/query/mapper/NotificationQueryMapper.java
  src/main/java/com/newbit/notification/query/service/NotificationQueryService.java
  src/main/resources/mappers/notification/NotificationMapper.xml
  src/test/java/com/newbit/notification/command/application/service/NotificationCommandServiceTest.java
  src/test/java/com/newbit/notification/query/service/NotificationQueryServiceTest.java
Labels: feat

#296 feat/Nbt 187 시리즈 삭제 기능 구현
  src/main/java/com/newbit/column/controller/SeriesController.java
  src/main/java/com/newbit/column/service/SeriesService.java
  src/test/java/com/newbit/column/service/SeriesServiceTest.java
Labels: feat

#283 Feat 댓글 작성 시 인증된 사용자만 가능하도록 기능 구현
  src/main/java/com/newbit/post/controller/CommentController.java
  src/main/java/com/newbit/post/dto/request/CommentCreateRequest.java
  src/main/java/com/newbit/post/service/CommentService.java
  src/test/java/com/newbit/post/service/CommentServiceTest.java
Labels: feat

#297 Nbt 190 시리즈 상세 조회 기능 구현
  src/main/java/com/newbit/column/controller/SeriesController.java
  src/main/java/com/newbit/column/dto/response/GetSeriesDetailResponseDto.java
  src/main/java/com/newbit/column/mapper/SeriesMapper.java
  src/main/java/com/newbit/column/service/SeriesService.java
  src/test/java/com/newbit/column/service/SeriesServiceTest.java
Labels: feat

#299 Nbt 203 be 댓글 삭제 기능 수정 회원 인증
  src/main/java/com/newbit/post/controller/CommentController.java
  src/main/java/com/newbit/post/service/CommentService.java
  src/test/java/com/newbit/post/service/CommentServiceTest.java
Labels: feat

#301 Nbt 157 be 회원 프로필 조회 기능
  src/main/java/com/newbit/user/controller/UserInfoController.java
  src/main/java/com/newbit/user/dto/response/OhterUserProfileDTO.java
  src/main/java/com/newbit/user/mapper/UserMapper.java
  src/main/java/com/newbit/user/service/UserQueryService.java
  src/main/resources/mappers/user/OhterUserProfile.xml
  src/test/java/com/newbit/user/service/ProfileServiceTest.java
Labels: feat

#302 Nbt 189 멘토가 생성한 시리즈 목록 조회 본인 전용 기능 구현
  src/main/java/com/newbit/column/controller/SeriesController.java
  src/main/java/com/newbit/column/dto/response/GetMySeriesListResponseDto.java
  src/main/java/com/newbit/column/mapper/SeriesMapper.java
  src/main/java/com/newbit/column/repository/SeriesRepository.java
  src/main/java/com/newbit/column/service/SeriesService.java
  src/test/java/com/newbit/column/service/SeriesServiceTest.java
Labels: feat

#304 Nbt 188 시리즈에 포함된 칼럼 목록 조회 기능 구현
  src/main/java/com/newbit/column/controller/SeriesController.java
  src/main/java/com/newbit/column/domain/Series.java
  src/main/java/com/newbit/column/dto/response/GetMySeriesListResponseDto.java
  src/main/java/com/newbit/column/dto/response/GetSeriesColumnsResponseDto.java
  src/main/java/com/newbit/column/dto/response/GetSeriesDetailResponseDto.java
  src/main/java/com/newbit/column/dto/response/UpdateSeriesResponseDto.java
  src/main/java/com/newbit/column/mapper/SeriesMapper.java
  src/main/java/com/newbit/column/service/SeriesService.java
  src/test/java/com/newbit/column/service/SeriesServiceTest.java
Labels: feat

#306 [BE] NBT-204 알림 테이블 수정에 따른 반영
  src/main/java/com/newbit/notification/command/application/dto/request/NotificationSendRequest.java
  src/main/java/com/newbit/notification/command/application/dto/response/NotificationSendResponse.java
  src/main/java/com/newbit/notification/command/application/service/NotificationCommandService.java
  src/main/java/com/newbit/notification/command/domain/aggregate/Notification.java
  src/main/java/com/newbit/notification/query/dto/NotificationResponse.java
  src/main/resources/mappers/notification/NotificationMapper.xml
  src/test/java/com/newbit/notification/command/application/service/NotificationCommandServiceTest.java
Labels: feat

#309 Nbt 158 be 멘토 프로필 조회 기능
  src/main/java/com/newbit/user/controller/UserInfoController.java
  src/main/java/com/newbit/user/dto/response/ColumnDTO.java
  src/main/java/com/newbit/user/dto/response/MentorProfileDTO.java
  src/main/java/com/newbit/user/dto/response/OhterUserProfileDTO.java
  src/main/java/com/newbit/user/dto/response/PostDTO.java
  src/main/java/com/newbit/user/dto/response/SeriesDTO.java
  src/main/java/com/newbit/user/mapper/UserMapper.java
  src/main/java/com/newbit/user/service/UserQueryService.java
  src/main/resources/mappers/user/MentorProfile.xml
  src/main/resources/mappers/user/OhterUserProfile.xml
  src/test/java/com/newbit/user/service/MentorinfoServiceTest.java
Labels: feat

#307 Nbt 113 be 커피챗 취소
  src/main/java/com/newbit/coffeechat/command/application/controller/CoffeechatCommandController.java
  src/main/java/com/newbit/coffeechat/command/application/dto/request/CoffeechatCancelRequest.java
  src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java
  src/main/java/com/newbit/coffeechat/command/domain/aggregate/Coffeechat.java
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/purchase/command/application/service/DiamondCoffeechatTransactionCommandService.java
  src/main/java/com/newbit/purchase/command/application/service/PurchaseCommandService.java
  src/main/java/com/newbit/purchase/command/application/service/SaleCommandService.java
  src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
  src/test/java/com/newbit/purchase/command/application/service/PurchaseCommandServiceTest.java
Labels: feat

#317 [NBT-154] [BE] 시리즈 구독 및 취소 기능 구현
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/subscription/controller/SubscriptionController.java
  src/main/java/com/newbit/subscription/dto/request/SubscriptionRequest.java
  src/main/java/com/newbit/subscription/dto/response/SubscriptionResponse.java
  src/main/java/com/newbit/subscription/dto/response/SubscriptionStatusResponse.java
  src/main/java/com/newbit/subscription/entity/Subscription.java
  src/main/java/com/newbit/subscription/entity/SubscriptionId.java
  src/main/java/com/newbit/subscription/repository/SubscriptionRepository.java
  src/main/java/com/newbit/subscription/service/SubscriptionManager.java
  src/main/java/com/newbit/subscription/service/SubscriptionService.java
  src/main/java/com/newbit/subscription/util/SubscriptionValidator.java
  src/test/java/com/newbit/like/integration/PostLikeServiceIntegrationTest.java
  src/test/java/com/newbit/subscription/integration/SubscriptionIntegrationTest.java
  src/test/java/com/newbit/subscription/service/SubscriptionServiceTest.java
Labels: feat

#319 Nbt 81 be 관리자 칼럼 등록 요청 승인 거절 기능 구현
  src/main/java/com/newbit/column/controller/AdminColumnController.java
  src/main/java/com/newbit/column/domain/Column.java
  src/main/java/com/newbit/column/domain/ColumnRequest.java
  src/main/java/com/newbit/column/dto/request/ApproveColumnRequestDto.java
  src/main/java/com/newbit/column/dto/request/RejectColumnRequestDto.java
  src/main/java/com/newbit/column/dto/response/AdminColumnResponseDto.java
  src/main/java/com/newbit/column/mapper/AdminColumnMapper.java
  src/main/java/com/newbit/column/service/AdminColumnService.java
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/test/java/com/newbit/column/service/AdminColumnServiceTest.java
Labels: feat

#316 Nbt 199 게시글 에러 코드 common 패키지의 공통 에러 양식으로 리팩토링
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/post/service/CommentService.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/CommentServiceTest.java
  src/test/java/com/newbit/post/service/PostServiceNoticeTest.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: refactor

#320 Nbt 82 be 관리자 칼럼 수정 요청 승인 거절 기능 구현
  src/main/java/com/newbit/column/controller/AdminColumnController.java
  src/main/java/com/newbit/column/domain/Column.java
  src/main/java/com/newbit/column/service/AdminColumnService.java
  src/test/java/com/newbit/column/service/AdminColumnServiceTest.java
Labels: feat

#324 Nbt 83 be 관리자 칼럼 삭제 요청 승인 거절 기능 구현
  src/main/java/com/newbit/column/controller/AdminColumnController.java
  src/main/java/com/newbit/column/service/AdminColumnService.java
  src/test/java/com/newbit/column/service/AdminColumnServiceTest.java
Labels: feat

#326 Nbt 142 be 회원 정지 기능
  src/main/java/com/newbit/auth/service/AuthService.java
  src/main/java/com/newbit/post/repository/CommentRepository.java
  src/main/java/com/newbit/post/repository/PostRepository.java
  src/main/java/com/newbit/user/entity/User.java
  src/main/java/com/newbit/user/service/SuspensionService.java
  src/test/java/com/newbit/auth/service/AuthLogOutServiceTest.java
  src/test/java/com/newbit/user/service/SuspensionLoginServiceTest.java
  src/test/java/com/newbit/user/service/SuspensionServiceTest.java
Labels: feat

#327 Nbt 74 be 리뷰 등록 기능 구현
  src/main/java/com/newbit/coffeechat/command/application/controller/ReviewCommandController.java
  src/main/java/com/newbit/coffeechat/command/application/dto/request/ReviewCreateRequest.java
  src/main/java/com/newbit/coffeechat/command/application/dto/response/ReviewCommandResponse.java
  src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java
  src/main/java/com/newbit/coffeechat/command/application/service/ReviewCommandService.java
  src/main/java/com/newbit/coffeechat/command/domain/aggregate/Review.java
  src/main/java/com/newbit/coffeechat/command/domain/repository/ReviewRepository.java
  src/main/java/com/newbit/coffeechat/command/infrastructure/repository/JpaReviewRepository.java
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/user/service/MentorService.java
  src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
  src/test/java/com/newbit/coffeechat/command/application/service/ReviewCommandServiceTest.java
Labels: feat

#328 Nbt 112 be 리뷰 삭제 기능 구현
  src/main/java/com/newbit/coffeechat/command/application/controller/ReviewCommandController.java
  src/main/java/com/newbit/coffeechat/command/application/service/ReviewCommandService.java
  src/main/java/com/newbit/coffeechat/command/domain/aggregate/Review.java
  src/main/java/com/newbit/coffeechat/command/domain/repository/ReviewRepository.java
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/test/java/com/newbit/coffeechat/command/application/service/ReviewCommandServiceTest.java
Labels: feat

#331 Nbt 108 be 멘토 목록 조회 기능 구현
  src/main/java/com/newbit/user/controller/UserInfoController.java
  src/main/java/com/newbit/user/dto/request/MentorListRequestDTO.java
  src/main/java/com/newbit/user/dto/response/MentorListResponseDTO.java
  src/main/java/com/newbit/user/mapper/UserMapper.java
  src/main/java/com/newbit/user/service/UserQueryService.java
  src/main/resources/mappers/user/MentorList.xml
  src/test/java/com/newbit/user/service/MentorListServiceTest.java
Labels: feat

#337 Nbt 185 정산 내역 계산 및 생성 기능 구현
  src/main/java/com/newbit/purchase/command/domain/aggregate/SaleHistory.java
  src/main/java/com/newbit/purchase/command/domain/repository/SaleHistoryRepository.java
  src/main/java/com/newbit/settlement/controller/MentorSettlementController.java
  src/main/java/com/newbit/settlement/entity/MonthlySettlementHistory.java
  src/main/java/com/newbit/settlement/repository/MonthlySettlementHistoryRepository.java
  src/main/java/com/newbit/settlement/service/MentorSettlementService.java
  src/test/java/com/newbit/settlement/service/MentorSettlementServiceTest.java
Labels: feat

#338 [BE] NBT-211 커피챗 관련 알림 발송 처리
  src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java
  src/main/java/com/newbit/coffeeletter/service/MessageServiceImpl.java
  src/main/java/com/newbit/notification/command/application/dto/response/NotificationSendResponse.java
  src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
  src/test/java/com/newbit/coffeeletter/service/MessageServiceTest.java
Labels: feat

#341 Nbt 183 멘토 정산 내역 목록 조회 기능 구현
  src/main/java/com/newbit/settlement/controller/MentorSettlementController.java
  src/main/java/com/newbit/settlement/dto/response/MentorSettlementListResponseDto.java
  src/main/java/com/newbit/settlement/dto/response/MentorSettlementSummaryDto.java
  src/main/java/com/newbit/settlement/repository/MonthlySettlementHistoryRepository.java
  src/main/java/com/newbit/settlement/service/MentorSettlementService.java
  src/test/java/com/newbit/settlement/service/MentorSettlementServiceTest.java
Labels: feat

#342 Nbt 184 멘토 정산 상세 내역 조회 기능 구현
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/settlement/controller/MentorSettlementController.java
  src/main/java/com/newbit/settlement/dto/response/MentorSettlementDetailResponseDto.java
  src/main/java/com/newbit/settlement/service/MentorSettlementService.java
  src/test/java/com/newbit/settlement/service/MentorSettlementServiceTest.java
Labels: feat

#345 Nbt 186 정산서 이메일 자동 발송 기능 구현
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/settlement/controller/MentorSettlementController.java
  src/main/java/com/newbit/settlement/service/MentorSettlementService.java
  src/test/java/com/newbit/settlement/service/MentorSettlementServiceTest.java
Labels: feat

#351 [BE] NBT-219 다이아 결제 후 회원 다이아 변경 다이아 내역 생성 구현
  src/main/java/com/newbit/payment/command/application/service/PaymentCommandService.java
  src/main/java/com/newbit/payment/command/application/service/RefundCommandService.java
  src/main/java/com/newbit/purchase/command/application/service/DiamondCoffeechatTransactionCommandService.java
  src/main/java/com/newbit/purchase/command/application/service/DiamondTransactionCommandService.java
  src/main/java/com/newbit/purchase/command/domain/aggregate/DiamondTransactionType.java
  src/test/java/com/newbit/payment/command/application/service/PaymentCommandServiceTest.java
  src/test/java/com/newbit/payment/command/application/service/RefundCommandServiceTest.java
  src/test/java/com/newbit/purchase/command/application/service/DiamondTransactionCommandServiceTest.java
Labels: feat

#354 Nbt 221 be 서비스 로직 수정에 따른 테스트 코드 수정
  src/test/java/com/newbit/auth/service/AuthServiceTest.java
  src/test/java/com/newbit/auth/service/CustomUserDetailsServiceTest.java
  src/test/java/com/newbit/user/service/UserServiceTest.java
Labels: fix

#358 fix: 댓글 삭제 시 postId 불일치 예외코드 수정 및 삭제된 댓글 예외 처리 개선
  src/main/java/com/newbit/post/service/CommentService.java
Labels: bug

#362 Nbt 229 be post create request dto 수정
  src/main/java/com/newbit/post/dto/request/PostCreateRequest.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: bug

#365 Nbt 228 칼럼 요청 controller test 오류 수정
  src/test/java/com/newbit/column/controller/ColumnRequestControllerTest.java
Labels: bug

#366 refactor: 에러 코드 도메인 코드 규칙 적용하여 수정
  src/main/java/com/newbit/common/exception/ErrorCode.java
Labels: refactor

#367 Nbt 213 be 커피챗 시간 확정 시 채팅방 생성
  src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java
Labels: feat

#372 Nbt 233 be 커피챗 취소 시 커피레터 채팅방 삭제
  src/main/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandService.java
  src/test/java/com/newbit/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
Labels: feat

#376 fix: 비회원 게시글 등록 시 NullPointerException 발생 문제 해결
  src/main/java/com/newbit/common/exception/ErrorCode.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: fix

#375 [BE] NBT-235 칼럼 등록시 시리즈 id도 같이 등록하는 식으로 수정
  src/main/java/com/newbit/column/dto/request/CreateColumnRequestDto.java
  src/main/java/com/newbit/column/mapper/ColumnMapper.java
  src/main/java/com/newbit/column/service/ColumnRequestService.java
  src/test/java/com/newbit/column/service/ColumnRequestServiceTest.java
Labels: feat

#382 feat: 컨트ë¡ix¬에서 입력값 오류 수정
  src/main/java/com/newbit/coffeechat/query/controller/CoffeechatQueryController.java
Labels: fix

#386 fix : mapper.xml ã수정
  src/main/resources/mappers/coffeechat/CoffeechatMapper.xml
Labels: bug

#388 refactor : 공통 에러 핸들러 주석 해제
  src/main/java/com/newbit/common/exception/GlobalExceptionHandler.java
Labels: feat

#379 [BE] NBT-215 시리즈에 새로운 칼럼 등록시 구독한 사용자들에게 알림 발송 기능구현
  src/main/java/com/newbit/column/service/AdminColumnService.java
  src/test/java/com/newbit/column/service/AdminColumnServiceTest.java
Labels: feat

#395 Nbt 244 java에서 point type 하드코딩 되어있는 부분 상수 클래스로 바꾸기
  src/main/java/com/newbit/coffeechat/command/application/service/ReviewCommandService.java
  src/main/java/com/newbit/like/service/PointRewardService.java
  src/main/java/com/newbit/post/service/CommentService.java
  src/main/java/com/newbit/post/service/PostService.java
  src/main/java/com/newbit/purchase/command/application/service/PointTransactionCommandService.java
  src/main/java/com/newbit/purchase/command/application/service/PurchaseCommandService.java
  src/main/java/com/newbit/purchase/command/domain/PointTypeConstants.java
  src/main/java/com/newbit/user/service/LoginService.java
  src/test/java/com/newbit/coffeechat/command/application/service/ReviewCommandServiceTest.java
  src/test/java/com/newbit/purchase/command/application/service/PointTransactionCommandServiceTest.java
Labels: refactor

#406 refactor : mentorEntity 대신 mentorId 가져오는 방식으로 수정
  src/main/java/com/newbit/coffeechat/query/controller/CoffeechatQueryController.java
  src/main/java/com/newbit/coffeechat/query/controller/ReviewQueryController.java
  src/main/java/com/newbit/user/service/MentorService.java
Labels: feat

#408 fix: NBT-157 오타 수정
  src/main/java/com/newbit/user/controller/UserInfoController.java
  src/main/java/com/newbit/user/dto/response/OtherUserProfileDTO.java
  src/main/java/com/newbit/user/mapper/UserMapper.java
  src/main/java/com/newbit/user/service/UserQueryService.java
  src/main/resources/mappers/user/OtherUserProfile.xml
  src/test/java/com/newbit/user/service/ProfileServiceTest.java
Labels: fix

#411 fix: Long mentorId로 수정
  src/main/java/com/newbit/column/domain/Column.java
  src/main/java/com/newbit/column/domain/Series.java
  src/main/java/com/newbit/column/mapper/ColumnMapper.java
  src/main/java/com/newbit/column/repository/ColumnRepository.java
  src/main/java/com/newbit/column/repository/ColumnRequestRepository.java
  src/main/java/com/newbit/column/repository/SeriesRepository.java
  src/main/java/com/newbit/column/service/AdminColumnService.java
  src/main/java/com/newbit/column/service/ColumnRequestService.java
  src/main/java/com/newbit/column/service/ColumnService.java
  src/main/java/com/newbit/column/service/SeriesService.java
  src/main/java/com/newbit/user/service/MentorService.java
  src/test/java/com/newbit/column/service/ColumnRequestServiceTest.java
  src/test/java/com/newbit/column/service/ColumnServiceTest.java
  src/test/java/com/newbit/column/service/SeriesServiceTest.java
Labels: bug

#413 Nbt 255 post 도메인 서비스 구현 요청
  src/main/java/com/newbit/post/controller/CommentController.java
  src/main/java/com/newbit/post/controller/PostController.java
  src/main/java/com/newbit/post/entity/Comment.java
  src/main/java/com/newbit/post/entity/Post.java
  src/main/java/com/newbit/post/repository/PostRepository.java
  src/main/java/com/newbit/post/service/CommentService.java
  src/main/java/com/newbit/post/service/PostService.java
  src/test/java/com/newbit/post/service/CommentServiceTest.java
  src/test/java/com/newbit/post/service/PostServiceTest.java
Labels: feat

#416 Nbt 257 정산 기능 mentor id로 수정
  src/main/java/com/newbit/settlement/controller/MentorSettlementController.java
  src/main/java/com/newbit/settlement/entity/MonthlySettlementHistory.java
  src/main/java/com/newbit/settlement/repository/MonthlySettlementHistoryRepository.java
  src/main/java/com/newbit/settlement/service/MentorSettlementService.java
  src/main/java/com/newbit/user/service/UserQueryService.java
  src/main/java/com/newbit/user/support/MailServiceSupport.java
  src/test/java/com/newbit/column/service/AdminColumnServiceTest.java
  src/test/java/com/newbit/column/service/ColumnServiceTest.java
  src/test/java/com/newbit/settlement/service/MentorSettlementServiceTest.java
Labels: fix

#420 Nbt 258 user 도메인 캡슐화 점검 코드 수정 및 msa 적용 시 수정 필요 목록 작성
  src/main/java/com/newbit/post/service/ReportCountService.java
  src/main/java/com/newbit/user/port/ReportCountPort.java
  src/main/java/com/newbit/user/service/SuspensionService.java
  src/test/java/com/newbit/user/service/SuspensionLoginServiceTest.java
  src/test/java/com/newbit/user/service/SuspensionServiceTest.java
Labels: fix

#428 Update README.md-프로젝트 개요 추가
  README.md
Labels: feat

#433 Nbt 261 칼럼 테스트 코드 수정
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/column/service/AdminColumnServiceTest.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/column/service/ColumnServiceTest.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/column/service/SeriesServiceTest.java
Labels: bug

#447 [BE] NBT-263 게시판 도메인 포인트 지급 리팩터링
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/CommentInternalService.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/CommentService.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostInternalService.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/CommentServiceTest.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/PostServiceNoticeTest.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/PostServiceTest.java
Labels: feat

#450 [BE] NBT-267 커피챗 도메인 팁 지급 리뷰 포인트 지급 리팩터링
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/ReviewCommandService.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/ReviewInternalService.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/domain/PointTypeConstants.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/ReviewCommandServiceTest.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/ReviewInternalServiceTest.java
Labels: fix

#455 api mapping 수정
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/controller/CommentController.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/controller/PostController.java
Labels: fix

#462 Nbt 275 s 3 설정 파일
  newbit-feature-service/build.gradle
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/s3/config/S3Config.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/s3/service/S3Uploader.java
Labels: feat

#482 Nbt 276 칼럼 및 시리즈 이미지 첨부 기능 추가
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/ColumnImageController.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/SeriesImageController.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/ImageService.java
Labels: feat

#485 [BE] NBT-277 커피챗 취소 db처리 로직과 외부 서비스 호출로직 분리
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatCommandService.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatInternalService.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatCommandServiceTest.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/coffeechat/command/application/service/CoffeechatInternalServiceTest.java
Labels: refactor

#486 [BE] NBT-288 구매 도메인 엔티티에 protected 어노테이션 적용하기
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/purchase/command/domain/aggregate/ColumnPurchaseHistory.java
Labels: feat

#501 Nbt 295 빈 시리즈 생성 가능하게 수정
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/dto/request/CreateSeriesRequestDto.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/SeriesService.java
Labels: fix

#517 [FE] NBT-301 프론트엔드 프로젝트 구조 생성
  newbit-frontend/.gitignore
  newbit-frontend/README.md
  newbit-frontend/index.html
  newbit-frontend/jsconfig.json
  newbit-frontend/package-lock.json
  newbit-frontend/package.json
  newbit-frontend/public/favicon.ico
  newbit-frontend/src/App.vue
  newbit-frontend/src/assets/chat-icon.png
  newbit-frontend/src/assets/diamond-icon.png
  newbit-frontend/src/assets/logo.png
  newbit-frontend/src/assets/notification-icon.png
  newbit-frontend/src/assets/profile.png
  newbit-frontend/src/components/common/Footer.vue
  newbit-frontend/src/components/common/Header.vue
  newbit-frontend/src/components/layout/DefaultLayout.vue
  newbit-frontend/src/components/layout/MyPageLayout.vue
  newbit-frontend/src/features/main/router.js
  newbit-frontend/src/features/main/views/MainView.vue
  newbit-frontend/src/main.js
  newbit-frontend/src/router/index.js
  newbit-frontend/vite.config.js
Labels: feat

#522 [FE] NBT-302 DefaultLayout 생성
  newbit-frontend/src/assets/image/chat-icon.png
  newbit-frontend/src/assets/image/diamond-icon.png
  newbit-frontend/src/assets/image/logo.png
  newbit-frontend/src/assets/image/notification-icon.png
  newbit-frontend/src/assets/image/profile.png
  newbit-frontend/src/assets/styles/global.css
  newbit-frontend/src/assets/styles/styleguide.css
  newbit-frontend/src/assets/styles/text-utilities.css
  newbit-frontend/src/components/common/Footer.vue
  newbit-frontend/src/components/common/Header.vue
  newbit-frontend/src/components/layout/DefaultLayout.vue
  newbit-frontend/src/features/main/views/MainView.vue
  newbit-frontend/src/main.js
  newbit-frontend/src/router/index.js
Labels: feat

#530 Nbt 296 시리즈 사용자용 조회 추가
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/SeriesController.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/domain/Series.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/SeriesService.java
Labels: feat

#548 Nbt 313 칼럼 시리즈 페이징 처리
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/ColumnController.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/controller/SeriesController.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/repository/ColumnRepository.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/repository/SeriesRepository.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/ColumnService.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/column/service/SeriesService.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/column/service/ColumnServiceTest.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/column/service/SeriesServiceTest.java
Labels: fix

#556 [BE] NBT-316 게시글 작성 transactional 분리
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostInternalService.java
  newbit-feature-service/src/main/java/com/newbit/newbitfeatureservice/post/service/PostService.java
  newbit-feature-service/src/test/java/com/newbit/newbitfeatureservice/post/service/PostServiceTest.java
Labels: refactor
